# Generated by Django 6.1 on 2026-08-19 10:36

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='Identifiant')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Dernière modification')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Date de suppression')),
                ('name', models.CharField(max_length=255, verbose_name="Nom de l'entreprise")),
                ('nif', models.CharField(blank=True, help_text="Numéro d'Identification Fiscale", max_length=50, null=True, verbose_name='NIF / STAT')),
                ('address', models.TextField(blank=True, null=True, verbose_name='Adresse')),
                ('currency', models.CharField(default='MGA', help_text='Code ISO 4217 de la devise (ex: MGA, EUR, USD)', max_length=3, verbose_name='Devise')),
            ],
            options={
                'verbose_name': 'Entreprise',
                'verbose_name_plural': 'Entreprises',
                'db_table': 'companies',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='FiscalYear',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='Identifiant')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Dernière modification')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Date de suppression')),
                ('label', models.CharField(help_text='Ex: Exercice 2026', max_length=50, verbose_name='Libellé')),
                ('start_date', models.DateField(verbose_name='Date de début')),
                ('end_date', models.DateField(verbose_name='Date de fin')),
                ('is_closed', models.BooleanField(default=False, verbose_name='Clôturé')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fiscal_years', to='companies.company', verbose_name='Entreprise')),
            ],
            options={
                'verbose_name': 'Exercice comptable',
                'verbose_name_plural': 'Exercices comptables',
                'db_table': 'fiscal_years',
                'ordering': ['-start_date'],
            },
        ),
        migrations.CreateModel(
            name='UserCompany',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='company_users', to='companies.company', verbose_name='Entreprise')),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='user_companies', to='accounts.role', verbose_name='Rôle')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_companies', to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur')),
            ],
            options={
                'verbose_name': 'Membre entreprise',
                'verbose_name_plural': 'Membres entreprise',
                'db_table': 'user_companies',
                'unique_together': {('user', 'company')},
            },
        ),
    ]
